In [1]:
#menggunakan numpy : yaitu untuk pengolahan matriks 
import numpy as np
list1 = [0, 1, 2, 3, 4]
array1d = np.array(list1)
array1d


array([0, 1, 2, 3, 4])

In [4]:
#tipe data
type(array1d)

numpy.ndarray

In [3]:
#menjumlahkan elemen array
array1d + 2

array([2, 3, 4, 5, 6])

In [5]:
#membuat array 2 dimensi (index 3x3)
list2 = [
    [0,1.5,2.8,3.7],
    [2.5,4.56,6.5,8.7],
    [3.6,6.7,9.6,12.5],]
array2d = np.array(list2)
array2d

array([[ 0.  ,  1.5 ,  2.8 ,  3.7 ],
       [ 2.5 ,  4.56,  6.5 ,  8.7 ],
       [ 3.6 ,  6.7 ,  9.6 , 12.5 ]])

In [6]:
#mengatur jenis data: float/int
array2d.astype('int')


array([[ 0,  1,  2,  3],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [8]:
#mengambil elemen tertentu pada array
# elemen pertama, sebanyak 1
x = array2d[:1, :1]
x

array([[0.]])

In [10]:
y = array2d[:1, :2]
y



array([[0. , 1.5]])

In [11]:
#operasi mean/min/max
array2d.mean()

5.221666666666667

In [12]:
array2d.max()

12.5

In [13]:
array2d.min()


0.0

In [14]:
#reshape : mengubah dimensi array dan Flattening : mengubah array jd 1 dimensi
array2d_new_dimension = array2d.reshape(4, 3)
array2d_new_dimension

array([[ 0.  ,  1.5 ,  2.8 ],
       [ 3.7 ,  2.5 ,  4.56],
       [ 6.5 ,  8.7 ,  3.6 ],
       [ 6.7 ,  9.6 , 12.5 ]])

In [15]:
array2d.flatten()

array([ 0.  ,  1.5 ,  2.8 ,  3.7 ,  2.5 ,  4.56,  6.5 ,  8.7 ,  3.6 ,
        6.7 ,  9.6 , 12.5 ])

In [16]:
#membuat array terisi data scr otomatis
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(start=20, stop=30, num=100, dtype=int)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23,
       23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30])

In [22]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.random.rand(3,4)

array([[0.40792926, 0.19234404, 0.26778456, 0.01467739],
       [0.79700954, 0.32566997, 0.3492724 , 0.05819539],
       [0.3629169 , 0.84605508, 0.3744209 , 0.94546884]])

In [27]:
np.random.randint(3, 10, size=[3,4])

array([[5, 8, 4, 5],
       [5, 8, 7, 7],
       [6, 5, 5, 4]])

In [29]:
np.random.choice(['Pria','Wanita'], size=10)



array(['Pria', 'Pria', 'Pria', 'Wanita', 'Pria', 'Pria', 'Wanita', 'Pria',
       'Pria', 'Pria'], dtype='<U6')